export const quotes = [
  { quote: "וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ — Love your neighbor as yourself.", source: "Leviticus 19:18", theme: "compassion" },
  { quote: "הִנֵּה מַה־טּוֹב וּמַה־נָּעִים שֶׁבֶת אַחִים גַּם־יָחַד", source: "Psalms 133:1", theme: "community" },
  { quote: "The human being is created b'tzelem Elohim — in the image of God.", source: "Genesis 1:27", theme: "dignity" },
  { quote: "Not by might, nor by power, but by My spirit.", source: "Zechariah 4:6", theme: "humility" },
  { quote: "The righteous person falls seven times and rises again.", source: "Proverbs 24:16", theme: "resilience" },
  { quote: "Who is wise? One who learns from every person.", source: "Pirkei Avot 4:1", theme: "wisdom" },
  { quote: "In a place where there are no humans, strive to be human.", source: "Pirkei Avot 2:5", theme: "ethics" },
  { quote: "The day is short, the work is great.", source: "Pirkei Avot 2:15", theme: "purpose" },
  { quote: "More than the calf wants to suck, the cow wants to give milk.", source: "Talmud, Pesachim 112a", theme: "generosity" },
  { quote: "The world stands on three things: Torah, service, and acts of kindness.", source: "Pirkei Avot 1:2", theme: "foundation" },
  { quote: "If I am not for myself, who will be for me? If I am only for myself, what am I?", source: "Hillel, Pirkei Avot 1:14", theme: "balance" },
  { quote: "The soul of a person is the lamp of God.", source: "Proverbs 20:27", theme: "inner_light" },
  { quote: "The beginning of wisdom is awe.", source: "Psalms 111:10", theme: "awe" },
  { quote: "The greatest thing in the world is to know how to belong to oneself.", source: "Montaigne (public domain)", theme: "self_knowledge" },
  { quote: "We are what we repeatedly do.", source: "Aristotle (public domain paraphrase)", theme: "habit" },
  { quote: "Every moment is a fresh beginning.", source: "T.S. Eliot (public domain)", theme: "renewal" },
  { quote: "The universe is full of magical things waiting for our wits to grow sharper.", source: "Eden Phillpotts (public domain)", theme: "wonder" },
  { quote: "The only journey is the one within.", source: "Rainer Maria Rilke (public domain)", theme: "introspection" },
  { quote: "Act as if what you do makes a difference. It does.", source: "William James (public domain)", theme: "agency" },
  { quote: "The mind is everything; what you think, you become.", source: "Early Buddhist teaching (public domain)", theme: "mindfulness" },
  { quote: "Seek peace and pursue it.", source: "Psalms 34:15", theme: "peace" },
  { quote: "Teach us to number our days, that we may gain a heart of wisdom.", source: "Psalms 90:12", theme: "mortality" },
  { quote: "Light is sown for the righteous.", source: "Psalms 97:11", theme: "hope" },
  { quote: "A soft answer turns away wrath.", source: "Proverbs 15:1", theme: "patience" },
  { quote: "Better a little with righteousness than great income with injustice.", source: "Proverbs 16:8", theme: "justice" },
  { quote: "As water reflects a face, so the heart reflects a person.", source: "Proverbs 27:19", theme: "character" },
  { quote: "For everything there is a season.", source: "Ecclesiastes 3:1", theme: "timing" },
  { quote: "A joyful heart is good medicine.", source: "Proverbs 17:22", theme: "joy" },
  { quote: "The wise of heart will receive commandments.", source: "Proverbs 10:8", theme: "teachability" },
  { quote: "The human spirit is the lamp of God.", source: "Proverbs 20:27", theme: "spirit" },
  { quote: "Many waters cannot quench love.", source: "Song of Songs 8:7", theme: "love" },
  { quote: "A person's pride will bring them low, but humility brings honor.", source: "Proverbs 29:23", theme: "humility" },
  { quote: "Say little and do much.", source: "Pirkei Avot 1:15", theme: "action" },
  { quote: "Who is strong? One who conquers their impulse.", source: "Pirkei Avot 4:1", theme: "self_mastery" },
  { quote: "In the place where you repent, even the righteous cannot stand.", source: "Talmud, Berakhot 34b", theme: "transformation" },
  { quote: "A good name is better than fine oil.", source: "Ecclesiastes 7:1", theme: "reputation" },
  { quote: "The highest wisdom is kindness.", source: "Talmud, Sota 14a", theme: "kindness" },
  { quote: "Do not separate yourself from the community.", source: "Pirkei Avot 2:4", theme: "community" },
  { quote: "Who is rich? One who rejoices in what they have.", source: "Pirkei Avot 4:1", theme: "gratitude" },
  { quote: "The reward is according to the effort.", source: "Pirkei Avot 5:26", theme: "effort" },
  { quote: "Silence is a fence around wisdom.", source: "Pirkei Avot 3:13", theme: "silence" },
  { quote: "A person is led in the way they wish to go.", source: "Talmud, Makkot 10b", theme: "intention" },
  { quote: "The world is a narrow bridge; the main thing is not to fear.", source: "Rabbi Nachman (public domain)", theme: "courage" },
  { quote: "Where there is no vision, the people perish.", source: "Proverbs 29:18", theme: "vision" },
  { quote: "Let justice roll down like waters.", source: "Amos 5:24", theme: "justice" },
  { quote: "The earth is full of the goodness of God.", source: "Psalms 33:5", theme: "gratitude" },
  { quote: "Wisdom gives life to those who have it.", source: "Ecclesiastes 7:12", theme: "wisdom" },
  { quote: "A faithful friend is a strong shelter.", source: "Ben Sira (public domain)", theme: "friendship" },
  { quote: "The candle of God searches the human soul.", source: "Proverbs 20:27", theme: "introspection" },
  { quote: "Do not rejoice when your enemy falls.", source: "Proverbs 24:17", theme: "restraint" },
  { quote: "A gentle tongue is a tree of life.", source: "Proverbs 15:4", theme: "speech" },
  { quote: "The wise person's eyes are in their head.", source: "Ecclesiastes 2:14", theme: "awareness" },
  { quote: "The heart of the discerning acquires knowledge.", source: "Proverbs 18:15", theme: "learning" },
  { quote: "Better is the end of a thing than its beginning.", source: "Ecclesiastes 7:8", theme: "patience" },
  { quote: "A person's gift makes room for them.", source: "Proverbs 18:16", theme: "talent" },
  { quote: "The spirit of a person sustains them in sickness.", source: "Proverbs 18:14", theme: "resilience" },
];

export function randomQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}
